/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BaseModal: typeof import('./src/components/BaseModal.vue')['default']
    GroupIcon: typeof import('./src/components/icons/GroupIcon.vue')['default']
    MessageList: typeof import('./src/components/MessageList.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    NavItem: typeof import('./src/components/NavItem.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TiptapEditor: typeof import('./src/components/TiptapEditor.vue')['default']
    Toasts: typeof import('./src/components/Toasts.vue')['default']
    UserIcon: typeof import('./src/components/icons/UserIcon.vue')['default']
  }
}
